package br.com.bimsearch.windows;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.io.File;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author wasotty
 */
public class ImagesPane extends javax.swing.JInternalFrame {

	/**
	 * Creates new form ImagesPane
	 */

	public ImagesPane() {
		initComponents();
	}

	// This method was made with the help of an Artificial Intelligence, unlike most of the project's code.
	// The main objective of this method is to 
	// 1. Receive the path where the image is.
	// 2. Show the image in the lbl made inside this JInternalFrame, this window.
	// 3. Modify the size, and center the image.
	public void showImage(String path) {
		try {
		System.out.println("Trying to load image from: " + path); // Criei isso porque estou tendo problemas com caminhso, quero ver onde está. Debugando
			File f = new File(path);
			if (!f.exists()) {
				JOptionPane.showMessageDialog(null, "Arquivo não encontrado: " + path);
				return;
			}
			System.out.println("Trying to load image from: " + path);
			ImageIcon icon = new ImageIcon(path);
			Image img = icon.getImage();

			int imgWidth = img.getWidth(null);
			int imgHeight = img.getHeight(null);
			int lblWidth = lblImage1.getWidth();
			int lblHeight = lblImage1.getHeight();

			// Se ainda não tiver tamanho definido, usa tamanho padrão
			if (lblWidth <= 0) lblWidth = 300;
			if (lblHeight <= 0) lblHeight = 300;

			// Calcula proporção para manter aspecto
			double widthRatio = (double) lblWidth / imgWidth;
			double heightRatio = (double) lblHeight / imgHeight;
			double scale = Math.min(widthRatio, heightRatio); // menor fator para caber

			int newWidth = (int) (imgWidth * scale);
			int newHeight = (int) (imgHeight * scale);

			Image scaledImg = img.getScaledInstance(newWidth, newHeight, Image.SCALE_SMOOTH);
			icon = new ImageIcon(scaledImg);

			lblImage1.setIcon(icon);
			lblImage1.setHorizontalAlignment(SwingConstants.CENTER);
			lblImage1.setVerticalAlignment(SwingConstants.CENTER);
			lblImage1.repaint();

		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, "Erro ao carregar imagem: " + e.getMessage());
		}
	}



	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents() {

		lblImage1 = new javax.swing.JLabel();

		setTitle("Images");
		setMinimumSize(new java.awt.Dimension(350, 564));
		setPreferredSize(new java.awt.Dimension(350, 564));


		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(lblImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(lblImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				);

		pack();
	}// </editor-fold>                        


	// Variables declaration - do not modify                     
	private javax.swing.JLabel lblImage1;
	// End of variables declaration                   
}

