/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.bimsearch.windows;

/**
 *
 * @author wasotty
 */
public class ListPane extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListPane
     */
    public ListPane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        sclPane = new javax.swing.JScrollPane();
        sclPanel = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(270, 564));
        setPreferredSize(new java.awt.Dimension(270, 564));

        sclPane.setViewportView(sclPanel);

        sclPanel.setLayout(new javax.swing.BoxLayout(sclPanel, javax.swing.BoxLayout.LINE_AXIS));
        sclPane.setViewportView(sclPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sclPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sclPane)
        );

        pack();
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JScrollPane sclPane;
    private javax.swing.JPanel sclPanel;
    // End of variables declaration                   
}

