package br.com.bimsearch.windows;
import java.sql.*;
import java.util.Arrays;
import javax.swing.JOptionPane;
import br.com.bimsearch.dal.DataAccessLayer; // since it is a package, java can find its path and import.
import br.com.bimsearch.windows.SearchWindow; // now we have the SearchWindow class here.
/**
 *
 * @author wasotty
 */

public class LoginWindow extends javax.swing.JFrame {
    
    Connection conec = null;
    PreparedStatement pst = null; 
    ResultSet rs = null;

	public void log(){
		//The line under will use the ? and look for the infos in the dataBase. 
		String sql = "select * from bimuser where username=? and password =?";
		try{
			pst = conec.prepareStatement(sql);
			pst.setString(1, txfUser.getText());
			// This following block treats the password, overwriting it from the garbage after its been used.
			char[] charsPassword = txfPassword.getPassword();
			String password = new String(charsPassword);
			pst.setString(2, password);

			Arrays.fill(charsPassword, ' ');
			//-
			rs = pst.executeQuery();

			if(rs.next()){ //If there is the user and password typed 
				//the line under looks which level of control the user has.
					String perfil = rs.getString(4);
				if(perfil.equals("admin")){
					//System.out.println(perfil); //test.
					SearchWindow main = new SearchWindow();
					main.setVisible(true);
					SearchWindow.menAdm.setEnabled(true);
					this.dispose();
					conec.close();
				}
				else{
					SearchWindow main = new SearchWindow();
					main.setVisible(true);
					this.dispose();
					conec.close();
				}
			}
			else{
				JOptionPane.showMessageDialog(null, "Invalid User or Password.");
			}
		}
		catch(Exception e){
			e.printStackTrace();
		}
	}


    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginWindow.class.getName());

    /**
     * Creates new form LoginWindow
     */
    public LoginWindow() {
        initComponents();
   	conec = DataAccessLayer.connector();     
    	//System.out.println(conec); //Prints if there was an exception.
	lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bimsearch/windows/images/loginIcons/ServerWaiting.png")));
	if(conec != null){
	lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bimsearch/windows/images/loginIcons/ServerConnected.png")));
	}
	else{
	lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bimsearch/windows/images/loginIcons/ServerDisconnected.png")));

	}
    }
 /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lblUser = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txfUser = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        txfPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BIM System - Login");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(365, 165));
        setResizable(false);

        lblUser.setText("User:");

        lblPassword.setText("Password:");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        

        lblStatus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUser)
                            .addComponent(lblPassword))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txfUser, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txfPassword))
                        .addGap(85, 85, 85))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogin)
                        .addGap(17, 17, 17))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUser)
                    .addComponent(txfUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatus)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnLogin)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(443, 252));
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {                                         
        log();
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginWindow().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPasswordField txfPassword;
    private javax.swing.JTextField txfUser;
    // End of variables declaration                   
}

