/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.bimsearch.windows;
import br.com.bimsearch.windows.User;
import javax.swing.JOptionPane;
/**
 *
 * @author wasotty
 */
public class SearchWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SearchWindow.class.getName());

    /**
     * Creates new form SearchWindow
     */
    public SearchWindow() {
        initComponents();
    }

/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        desktop = new javax.swing.JDesktopPane();
        desktopList = new javax.swing.JDesktopPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        lblId = new javax.swing.JLabel();
        lblPosition = new javax.swing.JLabel();
        lblProject = new javax.swing.JLabel();
        lblBy = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menSea = new javax.swing.JMenu();
        menFil = new javax.swing.JMenu();
        menAdm = new javax.swing.JMenu();
        menAdmAdd = new javax.swing.JMenuItem();
        menInf = new javax.swing.JMenu();
        menInfAbo = new javax.swing.JMenuItem();
        menOpt = new javax.swing.JMenu();
        menOptExi = new javax.swing.JMenuItem();
        menOptHel = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bim Search");

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopList.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopListLayout = new javax.swing.GroupLayout(desktopList);
        desktopList.setLayout(desktopListLayout);
        desktopListLayout.setHorizontalGroup(
            desktopListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopListLayout.createSequentialGroup()
                .addContainerGap(249, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        desktopListLayout.setVerticalGroup(
            desktopListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        lblId.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lblId.setText("ID:");

        lblPosition.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lblPosition.setText("SR Position:");

        lblProject.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lblProject.setText("Project:");

        lblBy.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lblBy.setText("By:");

        menSea.setText("Search");
        jMenuBar1.add(menSea);

        menFil.setText("Filters");
        jMenuBar1.add(menFil);

        menAdm.setText("Admin");
        menAdm.setEnabled(false);

        menAdmAdd.setText("Manage Users");
        menAdmAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menAdmAddActionPerformed(evt);
            }
        });
        menAdm.add(menAdmAdd);

        jMenuBar1.add(menAdm);

        menInf.setText("Info / License");
        menInf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menInfActionPerformed(evt);
            }
        });

        menInfAbo.setText("About");
        menInfAbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menInfAboActionPerformed(evt);
            }
        });
        menInf.add(menInfAbo);

        jMenuBar1.add(menInf);

        menOpt.setText("Options");

        menOptExi.setText("Exit");
        menOptExi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menOptExiActionPerformed(evt);
            }
        });
        menOpt.add(menOptExi);

        menOptHel.setText("Help");
        menOpt.add(menOptHel);

        jMenuBar1.add(menOpt);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(desktopList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblId)
                    .addComponent(lblPosition)
                    .addComponent(lblProject)
                    .addComponent(lblBy))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(desktop)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblId)
                        .addGap(18, 18, 18)
                        .addComponent(lblPosition)
                        .addGap(18, 18, 18)
                        .addComponent(lblProject)
                        .addGap(18, 18, 18)
                        .addComponent(lblBy)
                        .addGap(0, 422, Short.MAX_VALUE))
                    .addComponent(desktopList))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(900, 632));
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void menOptExiActionPerformed(java.awt.event.ActionEvent evt) {                                          
        int exit = JOptionPane.showConfirmDialog(null, "Are you sure you want to leave?","Yo!", JOptionPane.YES_NO_OPTION);
        if(exit == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }                                         

    private void menInfActionPerformed(java.awt.event.ActionEvent evt) {                                       
        WindowInfo about = new WindowInfo();
        about.setVisible(true);
    }                                      

    private void menInfAboActionPerformed(java.awt.event.ActionEvent evt) {                                          
        WindowInfo about = new WindowInfo();
        about.setVisible(true);
    }                                         

    private void menAdmAddActionPerformed(java.awt.event.ActionEvent evt) {                                          
        User users = new User();
        users.setVisible(true);
    }                                         
 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SearchWindow().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JDesktopPane desktopList;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBy;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblPosition;
    private javax.swing.JLabel lblProject;
    public static javax.swing.JMenu menAdm;
    private javax.swing.JMenuItem menAdmAdd;
    private javax.swing.JMenu menFil;
    private javax.swing.JMenu menInf;
    private javax.swing.JMenuItem menInfAbo;
    private javax.swing.JMenu menOpt;
    private javax.swing.JMenuItem menOptExi;
    private javax.swing.JMenuItem menOptHel;
    private javax.swing.JMenu menSea;
    // End of variables declaration                   
}

