package br.com.bimsearch.windows;
import br.com.bimsearch.windows.SearchWindow;
/**
 *
 * @author wasotty
 */
public class SearchFilter extends javax.swing.JFrame {
	private SearchWindow sc;
	private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SearchFilter.class.getName());

	/**
	 * Creates new form SearchFilter
	 */
	public SearchFilter(SearchWindow sc) {
		initComponents();        
		setLocationRelativeTo(null); 
		this.sc = sc;
	}
	
	public String getNameId(){
		return txtIdFil.getText();
	}


	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents() {

		lblIdFil = new javax.swing.JLabel();
		txtIdFil = new javax.swing.JTextField();
		btnOkFil = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		lblIdFil.setText("ID:");

		btnOkFil.setText("Ok");
		btnOkFil.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnOkFilActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addContainerGap()
					.addComponent(lblIdFil)
					.addGap(18, 18, 18)
					.addComponent(txtIdFil, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
					.addContainerGap(52, Short.MAX_VALUE))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
					.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addComponent(btnOkFil)
					.addContainerGap())
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(lblIdFil)
						.addComponent(txtIdFil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
					.addComponent(btnOkFil)
					.addContainerGap(12, Short.MAX_VALUE))
				);

		pack();
	}// </editor-fold>                        

	private void btnOkFilActionPerformed(java.awt.event.ActionEvent evt) {                                         
		sc.searchEl(getNameId());		
		dispose();
	}                                        

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
			logger.log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(() -> new SearchFilter(null).setVisible(true));
	}

	// Variables declaration - do not modify                     
	private javax.swing.JButton btnOkFil;
	private javax.swing.JLabel lblIdFil;
	private javax.swing.JTextField txtIdFil;
	// End of variables declaration                   
}

