package br.com.bimsearch.windows;
import br.com.bimsearch.windows.SearchWindow;


/**
 *
 * @author wasotty
 */
@SuppressWarnings("unused")
public class SizeConnecWindow extends javax.swing.JFrame {
	private SearchWindow parent;
	private int size, nConnections;
	private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SizeConnecWindow.class.getName());

	public SizeConnecWindow(SearchWindow parent) {
		this.parent = parent;
		initComponents();
	}

	public int getSizeEl(){
		try{
			size = Integer.parseInt(txtSizFil.getText().trim());
		}
		catch(Exception e){
			size = -1;
		}
		return size;
	}

	public int getNcon(){
		try{
			nConnections = Integer.parseInt(txtConFil.getText().trim());
		}
		catch(Exception e){
			nConnections = -1;
		}
		return nConnections;
	}

	public void saveInfo(){
		getSizeEl();
		getNcon();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	
	// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents() {

		btnOkFil = new javax.swing.JButton();
		lblSizFil = new javax.swing.JLabel();
		lblConFil = new javax.swing.JLabel();
		txtSizFil = new javax.swing.JTextField();
		txtConFil = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setResizable(false);

		btnOkFil.setText("Ok");
		btnOkFil.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnOkFilActionPerformed(evt);
			}
		});

		lblSizFil.setText("Size:");

		lblConFil.setText("Connections:");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
							.addGap(18, 18, 18)
							.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(lblConFil)
								.addComponent(lblSizFil))
							.addGap(18, 18, 18)
							.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(txtSizFil, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtConFil, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGroup(layout.createSequentialGroup()
							.addGap(104, 104, 104)
							.addComponent(btnOkFil)))
					.addContainerGap(23, Short.MAX_VALUE))
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
					.addGap(21, 21, 21)
					.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(lblSizFil)
						.addComponent(txtSizFil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
					.addGap(18, 18, 18)
					.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(lblConFil)
						.addComponent(txtConFil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
					.addComponent(btnOkFil)
					.addGap(15, 15, 15))
				);

		setSize(new java.awt.Dimension(295, 186));
		setLocationRelativeTo(null);
	}// </editor-fold>                        
	
	// Pass the variables and inputs to parent when the buttom is clicked.
	private void btnOkFilActionPerformed(java.awt.event.ActionEvent evt) {                                         
		parent.receiveFilterSize(getSizeEl(), getNcon());
		dispose();
	}                                        

	public static void main(String args[]) {
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
			logger.log(java.util.logging.Level.SEVERE, null, ex);
		}

		java.awt.EventQueue.invokeLater(() -> new SizeConnecWindow(null).setVisible(true));
	}

	// Variables declaration - do not modify                     
	private javax.swing.JButton btnOkFil;
	private javax.swing.JLabel lblConFil;
	private javax.swing.JLabel lblSizFil;
	private javax.swing.JTextField txtConFil;
	private javax.swing.JTextField txtSizFil;
	// End of variables declaration                   
}

