/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package br.com.bimsearch.windows;
import java.lang.Object;
import java.sql.*;
import br.com.bimsearch.dal.DataAccessLayer;
import javax.swing.JOptionPane;
/*/
 *
 * @author wasotty
 */
public class User extends javax.swing.JFrame {
   
	Connection conec = null;
	PreparedStatement pst = null;
	ResultSet rs = null;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(User.class.getName());

    /**
     * Creates new form User
     */
    public User() {
        initComponents();
	conec = DataAccessLayer.connector();
    }

	public void search(){
	
		String sql = "select * from bimuser where id=?";
		try{
			pst = conec.prepareStatement(sql);
			pst.setString(1, txtId.getText());
			rs = pst.executeQuery();
			if(rs.next()){
				txtLogin.setText(rs.getString(2));
				txtPassword.setText(rs.getString(3));
				cbbUser.setSelectedItem(rs.getString(4));
			}
			else{
				txtLogin.setText(null);
				cbbUser.setSelectedItem(null);
			}
		}
		catch(Exception e){
			JOptionPane.showMessageDialog(null, e);
		}

	}

	public void add(){
		String sql = "insert into bimuser(id, login, password, perfil) value (?,?,?,?)";
		try{
			pst = conec.prepareStatement(sql);
		
			pst.setString(1, txtId.getText());
			pst.setString(2, txtLogin.getText());
			pst.setString(3, txtPassword.getText());
			if(cbbUser.getSelectedItem() != null){
			pst.setString(4, cbbUser.getSelectedItem().toString());
			}
			else{
				JOptionPane.showMessageDialog(null, "You must choose a type of user");
			}

			if(txtLogin.getText().isEmpty() || txtPassword.getText().isEmpty() || txtId.getText().isEmpty() || cbbUser.getSelectedItem() == null){
				JOptionPane.showMessageDialog(null, "You must fill every field.");
			}
			else{
				int added = pst.executeUpdate();
			

				if(added > 0){
					txtLogin.setText(null);
					txtPassword.setText(null);
					txtId.setText(null);
					cbbUser.setSelectedItem(null);
				}
			
			}
		}
		catch(Exception e){
			JOptionPane.showMessageDialog(null, e);
		}

	}

	public void change(){
		
		String sql = "update bimuser set login=?, password=?, perfil=? where id=?";


		try{	
			pst = conec.prepareStatement(sql);
			pst.setString(1, txtLogin.getText());
			pst.setString(2, txtPassword.getText());
			pst.setString(3, cbbUser.getSelectedItem().toString());
			pst.setString(4, txtId.getText());
			
			if(txtLogin.getText().isEmpty() || txtPassword.getText().isEmpty() || txtId.getText().isEmpty() || cbbUser.getSelectedItem() == null){
				JOptionPane.showMessageDialog(null, "You must fill every field.");
			}
			else{
				int added = pst.executeUpdate();
			

				if(added > 0){
					txtLogin.setText(null);
					txtPassword.setText(null);
					txtId.setText(null);
					cbbUser.setSelectedItem(null);
				}
			
			}
		}
		catch(Exception e){
			JOptionPane.showMessageDialog(null, "The update did not work.");
		}
	}

	private void remove(){
		int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to remove this user?", "Yo!", JOptionPane.YES_NO_OPTION);

		if(confirm == JOptionPane.YES_OPTION){
			String sql = "delete from bimuser where id=?";
		

			try{
				pst = conec.prepareStatement(sql);
				pst.setString(1, txtId.getText());
				int removed = pst.executeUpdate();
				if(removed>0){
					JOptionPane.showMessageDialog(null, "User removed with success");
					txtLogin.setText(null);
					txtPassword.setText(null);
					txtId.setText(null);
					cbbUser.setSelectedItem(null);
				}	
			}
		
			catch(Exception e){
				JOptionPane.showMessageDialog(null, "The user wasn't removed");
			}

		}
	}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lblId2 = new javax.swing.JLabel();
        lblLogin2 = new javax.swing.JLabel();
        lblPassword2 = new javax.swing.JLabel();
        lblPerf = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtLogin = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        cbbUser = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Users");
        setPreferredSize(new java.awt.Dimension(350, 564));
        setResizable(false);

        lblId2.setText("ID:");

        lblLogin2.setText("Login:");

        lblPassword2.setText("Password:");

        lblPerf.setText("Perfil:");

        cbbUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "user" }));
        cbbUser.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cbbUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbUserActionPerformed(evt);
            }
        });

        btnAdd.setIcon(new javax.swing.ImageIcon("/home/wasotty/UTFPR/thirdperiod/projects/dataBaseInternship/br/com/bimsearch/windows/images/userIcons/addUser.png")); // NOI18N
        btnAdd.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        
	btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

	 btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
	
	 btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

	 btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });


        btnRemove.setIcon(new javax.swing.ImageIcon("/home/wasotty/UTFPR/thirdperiod/projects/dataBaseInternship/br/com/bimsearch/windows/images/userIcons/removeUser.png")); // NOI18N
        btnRemove.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSearch.setIcon(new javax.swing.ImageIcon("/home/wasotty/UTFPR/thirdperiod/projects/dataBaseInternship/br/com/bimsearch/windows/images/userIcons/search.png")); // NOI18N
        btnSearch.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnEdit.setIcon(new javax.swing.ImageIcon("/home/wasotty/UTFPR/thirdperiod/projects/dataBaseInternship/br/com/bimsearch/windows/images/userIcons/editUser.png")); // NOI18N
        btnEdit.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(lblPerf)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLogin2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblId2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(125, 125, 125))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblPassword2)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 30, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAdd)
                            .addComponent(btnSearch))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRemove)
                            .addComponent(btnEdit))
                        .addGap(65, 65, 65))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId2)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLogin2)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword2)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(lblPerf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbbUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnRemove))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEdit)
                    .addComponent(btnSearch))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(360, 594));
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void cbbUserActionPerformed(java.awt.event.ActionEvent evt) {                                        
       // A 
    }                                       

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {                                       
        search();
    }               

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {                                       
	add();
    }               

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {                                       
	change();
    }               
    
    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {                                       
	remove();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new User().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cbbUser;
    private javax.swing.JLabel lblId2;
    private javax.swing.JLabel lblLogin2;
    private javax.swing.JLabel lblPassword2;
    private javax.swing.JLabel lblPerf;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration                   
}

