package br.com.bimsearch.windows;

/**
 *
 * @author wasotty
 */
public class WindowInfo extends javax.swing.JFrame {

	private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(WindowInfo.class.getName());

	public WindowInfo() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	
	// <editor-fold defaultstate="collapsed" desc="Generated Code">                          


	private void initComponents() {
		// Create components
		lblInf1 = new javax.swing.JLabel("System developed to support the search for 3D models.");
		lblInf2 = new javax.swing.JLabel("Avoids duplicate modeling, saves time, and helps organize elements");
		lblInf3 = new javax.swing.JLabel("that can be reused in other projects.");
		lblAuthor = new javax.swing.JLabel("Made by: Vittor Masotti");
		lblLinkedIn = new javax.swing.JLabel("LinkedIn: Vittor Masotti");
		lblGitHub = new javax.swing.JLabel("GitHub: Masotti-Vittor");

		// Window settings
		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Information");
		setResizable(false);

		// Create a main panel with proper padding
		javax.swing.JPanel mainPanel = new javax.swing.JPanel();
		mainPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));

		// Use BoxLayout for vertical arrangement
		mainPanel.setLayout(new javax.swing.BoxLayout(mainPanel, javax.swing.BoxLayout.Y_AXIS));

		// Add information labels with proper alignment
		lblInf1.setAlignmentX(javax.swing.JComponent.CENTER_ALIGNMENT);
		lblInf2.setAlignmentX(javax.swing.JComponent.CENTER_ALIGNMENT);
		lblInf3.setAlignmentX(javax.swing.JComponent.CENTER_ALIGNMENT);

		// Add vertical spacing between components
		mainPanel.add(lblInf1);
		mainPanel.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 10)));
		mainPanel.add(lblInf2);
		mainPanel.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 5)));
		mainPanel.add(lblInf3);
		mainPanel.add(javax.swing.Box.createVerticalGlue());

		// Create footer panel for author info
		javax.swing.JPanel footerPanel = new javax.swing.JPanel();
		footerPanel.setLayout(new java.awt.BorderLayout());

		// Left-aligned author label
		javax.swing.JPanel leftPanel = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
		leftPanel.add(lblAuthor);

		// Right-aligned contact info
		javax.swing.JPanel rightPanel = new javax.swing.JPanel();
		rightPanel.setLayout(new javax.swing.BoxLayout(rightPanel, javax.swing.BoxLayout.Y_AXIS));
		rightPanel.add(lblLinkedIn);
		rightPanel.add(lblGitHub);

		footerPanel.add(leftPanel, java.awt.BorderLayout.WEST);
		footerPanel.add(rightPanel, java.awt.BorderLayout.EAST);

		// Add footer to main panel
		mainPanel.add(footerPanel);

		// Add main panel to window
		getContentPane().add(mainPanel);

		// Pack and center window
		pack();
		setLocationRelativeTo(null);
	}



	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
			logger.log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(() -> new WindowInfo().setVisible(true));
	}

	// Variables declaration - do not modify                     
	private javax.swing.JLabel lblAuthor;
	private javax.swing.JLabel lblGitHub;
	private javax.swing.JLabel lblInf1;
	private javax.swing.JLabel lblInf2;
	private javax.swing.JLabel lblInf3;
	private javax.swing.JLabel lblLinkedIn;
	// End of variables declaration                   
}

